<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="https://web.csulb.edu/~mopsteeg/engl418/structuredAuthoring/structuredAuthoring1.css" ?>
<!DOCTYPE document [ 
 <!ELEMENT document (title, introduction+, section+)>
<!ELEMENT section (sectionTitle, introduction+, topic+)>
<!ELEMENT topic (topicTitle, introduction+, (steps|list)*)>
<!ELEMENT steps (step+)>
<!ELEMENT list (listItem+)>
<!ELEMENT step (#PCDATA|action|note|warning|result)*>
<!ELEMENT listItem (#PCDATA|action|note|warning|result)*>
<!ELEMENT title (#PCDATA)>
<!ELEMENT sectionTitle (#PCDATA)>
<!ELEMENT topicTitle (#PCDATA)>
<!ELEMENT introduction (#PCDATA|note|warning|list)*>
<!ELEMENT result (#PCDATA|action)*>
<!ELEMENT note (#PCDATA|action)*>
<!ELEMENT warning (#PCDATA|action)*>
<!ELEMENT action (#PCDATA)>
]>
<document>
    <title>Making Vietnamese Rainbow Dessert</title>
    <introduction>
        This dessert is a childhood treat for many Vietnamese people. Its creamy, refreshing, and sweet taste can help you defeat the summer heat. Its various ingredients create a fun texture in your mouth upon consumption. The ingredients take between 2 and 3 hours to prepare but assembling the dessert only takes a few minutes. Let’s get into it!
    </introduction>
    <section>
      <sectionTitle>Ingredients</sectionTitle>
        <introduction>Most ingredients can be found in any Asian market.</introduction>
        <list>
            <listItem>2 tbsp of agar-agar powder 
              <note>It’s often sold in a small packet of 0.88 oz in Asian markets.</note>
            </listItem>
            <listItem>10 oz water chestnut</listItem>
            <listItem>3.5 oz peeled mung bean</listItem>
            <listItem>¾ cup of tapioca flour</listItem>
            <listItem>1.5 cups of coconut milk</listItem>
            <listItem>4 cups of coconut juice</listItem>
            <listItem>1.5 oz pandan leaves</listItem>
            <listItem>1 beetroot</listItem>
            <listItem>1 carrot</listItem>
            <listItem>Water</listItem>
            <listItem>Salt and sugar</listItem>
            <listItem>Shaved ice or crushed ice</listItem>
        </list>
    </section>
    <section>
      <sectionTitle>Utensils</sectionTitle>
        <list>
            <listItem>A blender or mixer</listItem>
            <listItem>A sieve</listItem>
            <listItem>Cheesecloth</listItem>
            <listItem>Some pots</listItem>
        </list>
    </section>
    <section>
      <sectionTitle>Preparing the ingredients</sectionTitle>
      <introduction>The preparation is divided by each component of the dish.</introduction>
        <topic>
            <topicTitle>Pandan leaves</topicTitle>
            <introduction>Pandan leaves are used for flavoring and coloring.</introduction>
            <steps>
                <step>Wash the leaves then finely chop them.</step>
                <step>Blend the leaves with 2 cups of water until fully mixed.</step>
                <step>Filter the mixture through a sieve and cheesecloth.</step>
                <step>Set aside ½ cup of the pandan juice for coloring.</step>
                <step>Mix the blended pandan leaves with 2 cups of warm water.</step>
                <step>Filter the mixture again to get roughly 4 cups of pandan juice.</step>
            </steps>
        </topic>
        <topic>
            <topicTitle>Carrot and Beetroot</topicTitle>
            <introduction>These two vegetables are used for natural color. They should be processed individually. You will have two cups of red and orange juice for later steps.</introduction>
            <steps>
                <step>Wash and peel the vegetables.</step>
                <step>Cut them into small pieces for blending.</step>
                <step>Blend each of them separately with ½ cup of water.</step>
                <step>Filter the blended mixture with a sieve and cheesecloth.</step>
            </steps>
        </topic>
        <topic>
            <topicTitle>Agar-agar powder</topicTitle>
            <introduction>This section uses a part of the product from preparing the pandan leaves. The result will be pandan jelly and coconut jelly.</introduction>
            <steps>
                <step>Soak half of the agar-agar (1 tbsp) into pandan juice for 20 minutes.</step>
                <step>Cook the pandan agar-agar on medium heat while stirring constantly.</step>
                <step>Reduce the heat to low when the mixture starts boiling.</step>
                <step>Add 5 tbsp of sugar, stir until the sugar dissolves, then turn off the heat.</step>
                <step>Pour the agar-agar into a mold and let it cool down completely before putting it into the fridge.</step>
                <step>Soak the remaining agar-agar (the last 1 tbsp) in the coconut juice for 20 minutes.</step>
                <step>Cook the coconut agar-agar the same way as the pandan one.
                  <note>You can save time by soaking the agar-agar in coconut juice before cooking the pandan mixture.</note>
                </step>
                <step>Once the agar-agar is set, cut or shred it into preferred shapes.</step>
            </steps>
        </topic>
        <topic>
            <topicTitle>Water chestnuts</topicTitle>
            <introduction>Before processing the chestnuts, you will need the coloring juices from pandan leaves, carrot, and beetroot.</introduction>
            <steps>
                <step>Wash, peel, and dice the water chestnuts into small bits. 
                  <note>If you use canned water chestnuts, they are already peeled.</note>
                </step>
                <step>Split the water chestnuts into 3 even parts.</step>
                <step>Add 1 tbsp of sugar into each part and mix thoroughly.</step>
                <step>Color each part in red, orange, and green by adding beetroot juice, carrot juice, and pandan juice.</step>
                <step>Soak the water chestnut for 15 minutes until the chestnut bits turn into their new color.</step>
                <step>Remove the water chestnut from the dye bath. Keep the colored juices.</step>
                <step>Mix each part of water chestnut with tapioca flour to fully coat the small cubes in a thin layer of flour. Remove the excessive flour.</step>
                <step>Boil the red chestnut cubes in 1.5 cups of water and the leftover beetroot juice. Stir lightly so they don’t stick to each other.</step>
                <step>When the cubes float up, remove them and soak them in an ice bath for 5 minutes.</step>
                <step>After 5 minutes, take the cubes out and let them dry. The result should be distinctively red chestnut bits wrapped in a translucent layer of red tapioca.</step>
                <step>Repeat the boiling, soaking, and drying processes with the orange and green water chestnut cubes.</step>
                <note>Fun fact: The red water chestnut cubes are the main reason this dish gets the name “Pomegranate Dessert” in Vietnamese because they resemble pomegranate seeds when cooked.</note>
            </steps>
        </topic>
        <topic>
            <topicTitle>Mung bean</topicTitle>
            <introduction>The mung bean paste will add a touch of creaminess to the dessert.</introduction>
            <steps>
                <step>Wash the mung beans then soak them in warm water for 1 hour.</step>
                <step>Pour mung beans into a pot and add water until reaching 1 inch above the bean’s surface.</step>
                <step>Cook the beans on medium heat until boiled.</step>
                <step>Remove white bubbles on the surface and excessive water, leaving the beans barely submerged.</step>
                <step>Cover the lid and cook for 20 minutes on low heat until the mung bean is softened and can be mashed with a spoon.</step>
                <step>While it’s still hot, add ½ cup of coconut milk, 1.5 tbsp of sugar, and a pinch of salt.</step>
                <step>Mash the mung bean mixture on extremely low heat until it becomes a smooth paste.</step>
            </steps>
        </topic>
        <topic>
            <topicTitle>Coconut milk</topicTitle>
            <introduction>Coconut milk is the base that binds all the ingredients together when assembling the dessert.</introduction>
            <steps>
                <step>Add 1 cup of coconut milk, ¾ cup of sugar, and a pinch of salt into a pot.</step>
                <step>Mix them on low heat until well combined.</step>
                <step>Remove from heat and let cool completely.</step>
            </steps>
        </topic>
    </section>
    <section>
      <sectionTitle>Assembling the dessert</sectionTitle>
      <introduction>All components should be either at room temperature or fridge temperature.</introduction>
        <steps>
          <step>All components of the dish should be either at room temperature or fridge temperature.</step>
          <step>Add shaved ice into a bowl.</step>
          <step>Add water chestnut cubes, coconut and pandan jelly, then mung bean paste on top of the ice. Spread them around the bowl.</step>
          <step>Pour a preferred amount of coconut milk on top.</step>
        </steps>  
        <result>And voilà! You’ve successfully made a fun and refreshing Vietnamese dish - the Rainbow Dessert (or “Jelly and Pomegranate chè” in Vietnamese).</result>
    </section>
</document>
